'use client';
import { useState, useEffect, useCallback } from 'react';
import { createBrowserClient } from '@supabase/ssr';
const ADMIN_PASSWORD='Gas05720572!';
const ALDERMEN:Record<number,string>={1:'Valencia Hall',2:'Billie Joe Frazier',3:'Sarah Carter-Smith',4:'Felicia Bridgewater-Irving',5:'Benjamin Davis',6:'Curtis Moroney'};
const PROFANITY=['fuck','shit','ass','bitch','damn','crap','piss','dick','cock','pussy','bastard','nigger','nigga','faggot','retard','whore','slut','cunt'];
function hasProfanity(t:string){return PROFANITY.some(w=>t.toLowerCase().includes(w));}
function MiniBar({value,max,color}:{value:number;max:number;color:string}){return(<div style={{background:'rgba(255,255,255,0.06)',borderRadius:4,height:6,flex:1}}><div style={{width:`${max>0?Math.round((value/max)*100):0}%`,height:'100%',borderRadius:4,background:color,transition:'width 0.6s ease'}}/></div>);}
function Stat({label,value,sub,color,icon}:any){return(<div style={{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:16,padding:'20px 22px',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',top:0,right:0,width:80,height:80,borderRadius:'0 16px 0 80px',background:color,opacity:0.08}}/><div style={{fontSize:28,marginBottom:6}}>{icon}</div><div style={{fontSize:32,fontWeight:900,color:'#fff',lineHeight:1}}>{value}</div><div style={{fontSize:12,color:'rgba(255,255,255,0.5)',marginTop:4,fontWeight:600,textTransform:'uppercase',letterSpacing:'0.08em'}}>{label}</div>{sub&&<div style={{fontSize:11,color:color,marginTop:6,fontWeight:700}}>{sub}</div>}</div>);}
const SC:Record<string,string>={pending:'#fbbf24',confirmed:'#22d3ee',acknowledged:'#a78bfa',in_progress:'#38bdf8',resolved:'#34d399',ignored:'#f87171',closed:'#a1a1aa',overdue:'#fb923c'};
export default function AdminDashboard(){
  const [auth,setAuth]=useState(false);
  const [pw,setPw]=useState('');
  const [pwErr,setPwErr]=useState(false);
  const [tab,setTab]=useState<'overview'|'reports'|'moderation'|'aldermen'>('overview');
  const [reports,setReports]=useState<any[]>([]);
  const [loading,setLoading]=useState(true);
  const [editR,setEditR]=useState<any>(null);
  const [editDesc,setEditDesc]=useState('');
  const [editStatus,setEditStatus]=useState('');
  const [saving,setSaving]=useState(false);
  const supabase=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
  const load=useCallback(async()=>{setLoading(true);const{data}=await supabase.from('reports').select('*').order('created_at',{ascending:false});setReports(data??[]);setLoading(false);},[]);
  useEffect(()=>{if(auth)load();},[auth,load]);
  async function delReport(id:string){if(!confirm('Delete permanently?'))return;await supabase.from('reports').delete().eq('id',id);setReports(r=>r.filter(x=>x.id!==id));}
  async function saveEdit(){setSaving(true);await supabase.from('reports').update({description:editDesc,status:editStatus}).eq('id',editR.id);setReports(r=>r.map(x=>x.id===editR.id?{...x,description:editDesc,status:editStatus}:x));setEditR(null);setSaving(false);}
  async function setStatus(id:string,status:string){await supabase.from('reports').update({status}).eq('id',id);setReports(r=>r.map(x=>x.id===id?{...x,status}:x));}
  if(!auth)return(<div style={{minHeight:'100vh',background:'#060610',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:'system-ui'}}><div style={{width:340,padding:40,background:'rgba(255,255,255,0.04)',border:'1px solid rgba(168,85,247,0.3)',borderRadius:24,textAlign:'center'}}><div style={{fontSize:48,marginBottom:16}}>🏛️</div><div style={{fontSize:22,fontWeight:900,color:'#fff',marginBottom:4}}>Admin Access</div><div style={{fontSize:13,color:'rgba(255,255,255,0.4)',marginBottom:28}}>We The People 39120</div><input type="password" placeholder="Password" value={pw} onChange={e=>{setPw(e.target.value);setPwErr(false);}} onKeyDown={e=>e.key==='Enter'&&(pw===ADMIN_PASSWORD?setAuth(true):setPwErr(true))} style={{width:'100%',height:48,borderRadius:12,border:`1px solid ${pwErr?'#f87171':'rgba(255,255,255,0.1)'}`,background:'rgba(255,255,255,0.06)',color:'#fff',fontSize:14,padding:'0 16px',outline:'none',boxSizing:'border-box',marginBottom:12}}/>{pwErr&&<div style={{color:'#f87171',fontSize:12,marginBottom:12}}>Incorrect password</div>}<button onClick={()=>pw===ADMIN_PASSWORD?setAuth(true):setPwErr(true)} style={{width:'100%',height:48,borderRadius:12,background:'linear-gradient(135deg,#7c3aed,#a855f7)',border:'none',color:'#fff',fontSize:15,fontWeight:700,cursor:'pointer'}}>Enter Dashboard</button></div></div>);
  const total=reports.length,resolved=reports.filter(r=>r.status==='resolved').length,pending=reports.filter(r=>['pending','confirmed'].includes(r.status)).length,ignored=reports.filter(r=>r.status==='ignored').length,withResp=reports.filter(r=>r.alderman_response).length,flagged=reports.filter(r=>r.description&&hasProfanity(r.description)),rate=total>0?Math.round((resolved/total)*100):0;
  const wardStats=Object.entries(ALDERMEN).map(([w,name])=>{const wr=reports.filter(r=>r.ward_number===Number(w));const res=wr.filter(r=>r.status==='resolved').length,ign=wr.filter(r=>r.status==='ignored').length,resp=wr.filter(r=>r.alderman_response).length,score=wr.length>0?Math.round(((res+resp*0.5)/wr.length)*100):0;return{ward:Number(w),name,total:wr.length,resolved:res,ignored:ign,responded:resp,score};}).sort((a,b)=>b.score-a.score);
  const catCounts:Record<string,number>={};reports.forEach(r=>{catCounts[r.category]=(catCounts[r.category]??0)+1;});const topCats=Object.entries(catCounts).sort((a,b)=>b[1]-a[1]).slice(0,6);
  const days7:Record<string,number>={};for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days7[d.toLocaleDateString('en-US',{weekday:'short'})]=0;}reports.forEach(r=>{const k=new Date(r.created_at).toLocaleDateString('en-US',{weekday:'short'});if(k in days7)days7[k]++;});const maxDay=Math.max(...Object.values(days7),1);
  const TABS=[{id:'overview',label:'Overview',icon:'📊'},{id:'reports',label:`Reports (${total})`,icon:'📋'},{id:'moderation',label:`Moderation${flagged.length>0?' 🔴 '+flagged.length:''}`,icon:'🛡️'},{id:'aldermen',label:'Aldermen',icon:'🏛️'}];
  return(<div style={{minHeight:'100vh',background:'#060610',color:'#fff',fontFamily:'system-ui',paddingBottom:40}}>
    <div style={{borderBottom:'1px solid rgba(255,255,255,0.07)',padding:'16px 24px',display:'flex',alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:50,background:'rgba(6,6,16,0.95)',backdropFilter:'blur(20px)'}}>
      <div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:38,height:38,borderRadius:10,background:'linear-gradient(135deg,#7c3aed,#a855f7)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:20}}>🏛️</div><div><div style={{fontWeight:900,fontSize:16}}>WTP 39120 Admin</div><div style={{fontSize:11,color:'rgba(255,255,255,0.4)'}}>Natchez, Mississippi</div></div></div>
      <div style={{display:'flex',gap:8}}><button onClick={load} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:8,color:'rgba(255,255,255,0.6)',fontSize:12,padding:'6px 14px',cursor:'pointer',fontWeight:600}}>↺ Refresh</button><button onClick={()=>setAuth(false)} style={{background:'rgba(248,113,113,0.12)',border:'1px solid rgba(248,113,113,0.25)',borderRadius:8,color:'#f87171',fontSize:12,padding:'6px 14px',cursor:'pointer',fontWeight:600}}>Sign Out</button></div>
    </div>
    <div style={{display:'flex',gap:4,padding:'16px 24px 0',overflowX:'auto'}}>{TABS.map(t=>(<button key={t.id} onClick={()=>setTab(t.id as any)} style={{padding:'8px 18px',borderRadius:10,border:'none',cursor:'pointer',fontWeight:700,fontSize:13,whiteSpace:'nowrap',background:tab===t.id?'linear-gradient(135deg,#7c3aed,#a855f7)':'rgba(255,255,255,0.04)',color:tab===t.id?'#fff':'rgba(255,255,255,0.5)'}}>{t.icon} {t.label}</button>))}</div>
    <div style={{padding:24}}>
      {tab==='overview'&&<div style={{display:'flex',flexDirection:'column',gap:24}}>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:12}}>
          <Stat label="Total Reports" value={total} color="#a855f7" icon="📋" sub={`+${reports.filter(r=>new Date(r.created_at)>new Date(Date.now()-7*86400000)).length} this week`}/>
          <Stat label="Resolved" value={resolved} color="#34d399" icon="✅" sub={`${rate}% rate`}/>
          <Stat label="Pending" value={pending} color="#fbbf24" icon="⏳" sub="Awaiting action"/>
          <Stat label="Ignored" value={ignored} color="#f87171" icon="🚨" sub="No response"/>
          <Stat label="Responses" value={withResp} color="#38bdf8" icon="💬" sub="Alderman replied"/>
          <Stat label="Flagged" value={flagged.length} color="#fb923c" icon="⚠️" sub="Needs review"/>
        </div>
        <div style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:16,padding:24}}>
          <div style={{fontSize:12,fontWeight:700,color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:20}}>Reports — Last 7 Days</div>
          <div style={{display:'flex',alignItems:'flex-end',gap:8,height:90}}>{Object.entries(days7).map(([day,count])=>(<div key={day} style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',gap:4}}><div style={{fontSize:11,fontWeight:700,color:'#a855f7'}}>{count||''}</div><div style={{width:'100%',borderRadius:'4px 4px 0 0',background:'linear-gradient(180deg,#a855f7,#7c3aed)',height:`${Math.max((count/maxDay)*70,count>0?8:2)}px`,transition:'height 0.5s ease'}}/><div style={{fontSize:10,color:'rgba(255,255,255,0.35)',fontWeight:600}}>{day}</div></div>))}</div>
        </div>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
          <div style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:16,padding:20}}><div style={{fontSize:12,fontWeight:700,color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:16}}>Top Issues</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{topCats.map(([cat,count])=>(<div key={cat} style={{display:'flex',alignItems:'center',gap:10}}><div style={{fontSize:12,color:'rgba(255,255,255,0.7)',width:100,fontWeight:600,textTransform:'capitalize',flexShrink:0}}>{cat.replace(/_/g,' ')}</div><MiniBar value={count} max={topCats[0]?.[1]||1} color="#a855f7"/><div style={{fontSize:12,fontWeight:700,color:'#a855f7',width:20,textAlign:'right'}}>{count}</div></div>))}</div></div>
          <div style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:16,padding:20}}><div style={{fontSize:12,fontWeight:700,color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:16}}>Alderman Spotlight</div>{wardStats[0]&&<div style={{marginBottom:12,padding:14,borderRadius:12,background:'rgba(52,211,153,0.08)',border:'1px solid rgba(52,211,153,0.2)'}}><div style={{fontSize:10,fontWeight:700,color:'#34d399',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:4}}>🏆 Most Responsive</div><div style={{fontWeight:800,fontSize:14,color:'#fff'}}>{wardStats[0].name}</div><div style={{fontSize:12,color:'rgba(255,255,255,0.5)',marginTop:2}}>Ward {wardStats[0].ward} · {wardStats[0].score}% · {wardStats[0].resolved} resolved</div></div>}{wardStats.length>1&&<div style={{padding:14,borderRadius:12,background:'rgba(248,113,113,0.08)',border:'1px solid rgba(248,113,113,0.2)'}}><div style={{fontSize:10,fontWeight:700,color:'#f87171',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:4}}>⚠️ Needs Attention</div><div style={{fontWeight:800,fontSize:14,color:'#fff'}}>{wardStats[wardStats.length-1].name}</div><div style={{fontSize:12,color:'rgba(255,255,255,0.5)',marginTop:2}}>Ward {wardStats[wardStats.length-1].ward} · {wardStats[wardStats.length-1].score}% · {wardStats[wardStats.length-1].ignored} ignored</div></div>}</div>
        </div>
      </div>}
      {tab==='reports'&&<div style={{display:'flex',flexDirection:'column',gap:8}}>{loading?<div style={{textAlign:'center',padding:40,color:'rgba(255,255,255,0.3)'}}>Loading...</div>:reports.map(r=>(<div key={r.id} style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:12,padding:'14px 16px',display:'flex',alignItems:'center',gap:12}}><div style={{flex:1,minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:4,flexWrap:'wrap'}}><span style={{fontSize:11,fontWeight:700,color:'#a855f7',textTransform:'uppercase'}}>{r.category?.replace(/_/g,' ')}</span><span style={{fontSize:10,padding:'2px 8px',borderRadius:20,background:(SC[r.status]||'#aaa')+'22',color:SC[r.status]||'#aaa',fontWeight:700}}>{r.status}</span><span style={{fontSize:10,color:'rgba(255,255,255,0.3)',marginLeft:'auto'}}>W{r.ward_number} · {new Date(r.created_at).toLocaleDateString()}</span></div><div style={{fontSize:13,color:'rgba(255,255,255,0.7)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.description||'No description'}</div></div><div style={{display:'flex',gap:6,flexShrink:0}}><select value={r.status} onChange={e=>setStatus(r.id,e.target.value)} style={{background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:8,color:'#fff',fontSize:11,padding:'4px 6px',cursor:'pointer'}}>{['pending','confirmed','acknowledged','in_progress','resolved','ignored','closed','overdue'].map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>{setEditR(r);setEditDesc(r.description||'');setEditStatus(r.status);}} style={{padding:'4px 10px',borderRadius:8,background:'rgba(168,85,247,0.15)',border:'1px solid rgba(168,85,247,0.3)',color:'#a855f7',fontSize:11,cursor:'pointer',fontWeight:700}}>Edit</button><button onClick={()=>delReport(r.id)} style={{padding:'4px 10px',borderRadius:8,background:'rgba(248,113,113,0.1)',border:'1px solid rgba(248,113,113,0.2)',color:'#f87171',fontSize:11,cursor:'pointer',fontWeight:700}}>Del</button></div></div>))}</div>}
      {tab==='moderation'&&<div style={{display:'flex',flexDirection:'column',gap:16}}><div style={{padding:16,borderRadius:12,background:'rgba(251,146,60,0.08)',border:'1px solid rgba(251,146,60,0.2)'}}><div style={{fontWeight:700,fontSize:14,color:'#fb923c',marginBottom:6}}>⚠️ Auto-Moderation Active</div><div style={{fontSize:13,color:'rgba(255,255,255,0.5)',lineHeight:1.6}}>Reports containing profanity are flagged for your review before appearing publicly.</div></div><div style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:16,padding:20}}><div style={{fontSize:12,fontWeight:700,color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.1em',marginBottom:12}}>Blocked Words ({PROFANITY.length})</div><div style={{display:'flex',flexWrap:'wrap',gap:6}}>{PROFANITY.map(w=><span key={w} style={{padding:'3px 10px',borderRadius:20,background:'rgba(248,113,113,0.1)',border:'1px solid rgba(248,113,113,0.2)',color:'#f87171',fontSize:11,fontWeight:600}}>{w[0]}{'*'.repeat(Math.max(w.length-2,1))}{w[w.length-1]}</span>)}</div></div>{flagged.length===0?<div style={{textAlign:'center',padding:40,background:'rgba(52,211,153,0.04)',border:'1px solid rgba(52,211,153,0.1)',borderRadius:16}}><div style={{fontSize:40,marginBottom:8}}>✅</div><div style={{fontWeight:700,color:'#34d399',fontSize:16}}>All clear</div></div>:<div style={{display:'flex',flexDirection:'column',gap:8}}><div style={{fontSize:13,fontWeight:700,color:'#fb923c'}}>{flagged.length} flagged:</div>{flagged.map(r=><div key={r.id} style={{background:'rgba(251,146,60,0.06)',border:'1px solid rgba(251,146,60,0.2)',borderRadius:12,padding:16}}><div style={{fontSize:12,color:'rgba(255,255,255,0.4)',marginBottom:6}}>Ward {r.ward_number} · {new Date(r.created_at).toLocaleDateString()}</div><div style={{fontSize:14,color:'#fff',marginBottom:12}}>{r.description}</div><div style={{display:'flex',gap:8}}><button onClick={()=>setStatus(r.id,'pending')} style={{padding:'6px 14px',borderRadius:8,background:'rgba(52,211,153,0.15)',border:'1px solid rgba(52,211,153,0.3)',color:'#34d399',fontSize:12,cursor:'pointer',fontWeight:700}}>✓ Approve</button><button onClick={()=>delReport(r.id)} style={{padding:'6px 14px',borderRadius:8,background:'rgba(248,113,113,0.1)',border:'1px solid rgba(248,113,113,0.2)',color:'#f87171',fontSize:12,cursor:'pointer',fontWeight:700}}>🗑 Delete</button></div></div>)}</div>}</div>}
      {tab==='aldermen'&&<div style={{display:'flex',flexDirection:'column',gap:10}}>{wardStats.map((w,i)=><div key={w.ward} style={{background:'rgba(255,255,255,0.03)',border:`1px solid ${w.score>60?'rgba(52,211,153,0.25)':w.score>30?'rgba(251,191,36,0.25)':'rgba(248,113,113,0.25)'}`,borderRadius:16,padding:'18px 20px'}}><div style={{display:'flex',alignItems:'center',gap:12,marginBottom:12}}><div style={{width:34,height:34,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:15,fontWeight:900,background:w.score>60?'rgba(52,211,153,0.2)':w.score>30?'rgba(251,191,36,0.2)':'rgba(248,113,113,0.2)',color:w.score>60?'#34d399':w.score>30?'#fbbf24':'#f87171'}}>{i+1}</div><div style={{flex:1}}><div style={{fontWeight:800,fontSize:15,color:'#fff'}}>{w.name}</div><div style={{fontSize:12,color:'rgba(255,255,255,0.4)'}}>Ward {w.ward}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:26,fontWeight:900,color:w.score>60?'#34d399':w.score>30?'#fbbf24':'#f87171'}}>{w.score}%</div><div style={{fontSize:10,color:'rgba(255,255,255,0.3)',textTransform:'uppercase',letterSpacing:'0.08em'}}>Score</div></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginBottom:10}}>{[{l:'Total',v:w.total,c:'#a855f7'},{l:'Resolved',v:w.resolved,c:'#34d399'},{l:'Ignored',v:w.ignored,c:'#f87171'},{l:'Responded',v:w.responded,c:'#38bdf8'}].map(s=><div key={s.l} style={{textAlign:'center',padding:'8px 4px',borderRadius:8,background:'rgba(255,255,255,0.03)'}}><div style={{fontSize:20,fontWeight:900,color:s.c}}>{s.v}</div><div style={{fontSize:10,color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.06em'}}>{s.l}</div></div>)}</div><MiniBar value={w.score} max={100} color={w.score>60?'#34d399':w.score>30?'#fbbf24':'#f87171'}/></div>)}</div>}
    </div>
    {editR&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.85)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:100,padding:20}}><div style={{background:'#0f0f1a',border:'1px solid rgba(168,85,247,0.3)',borderRadius:20,padding:28,width:'100%',maxWidth:480}}><div style={{fontWeight:800,fontSize:18,color:'#fff',marginBottom:20}}>Edit Report</div><textarea value={editDesc} onChange={e=>setEditDesc(e.target.value)} rows={4} style={{width:'100%',borderRadius:10,border:'1px solid rgba(255,255,255,0.1)',background:'rgba(255,255,255,0.05)',color:'#fff',fontSize:14,padding:12,outline:'none',resize:'vertical',boxSizing:'border-box',marginBottom:12}}/><select value={editStatus} onChange={e=>setEditStatus(e.target.value)} style={{width:'100%',height:44,borderRadius:10,border:'1px solid rgba(255,255,255,0.1)',background:'rgba(255,255,255,0.05)',color:'#fff',fontSize:14,padding:'0 12px',outline:'none',marginBottom:16}}>{['pending','confirmed','acknowledged','in_progress','resolved','ignored','closed','overdue'].map(s=><option key={s} value={s}>{s}</option>)}</select><div style={{display:'flex',gap:10}}><button onClick={saveEdit} disabled={saving} style={{flex:1,height:44,borderRadius:10,background:'linear-gradient(135deg,#7c3aed,#a855f7)',border:'none',color:'#fff',fontSize:14,fontWeight:700,cursor:'pointer',opacity:saving?0.7:1}}>{saving?'Saving...':'Save'}</button><button onClick={()=>setEditR(null)} style={{flex:1,height:44,borderRadius:10,background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',color:'rgba(255,255,255,0.6)',fontSize:14,fontWeight:700,cursor:'pointer'}}>Cancel</button></div></div></div>}
  </div>);
}
// admin v2
